env:
  browser: true
  commonjs: true
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - html
  - '@tivac/svelte'
globals:
  ym: true
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console: off
  no-alert: error
  no-eval: error
  arrow-parens:
    - error
    - always
  curly:
    - error
    - all
  template-curly-spacing:
    - error
    - always
